SELECT
    T1.EXCEPTION,
    T1.MODULE,
    T1.SUBSYSTEM,
    T1.HELPURL,
    T1.DATAPARTITION,
    T1.CREATEDDATETIME,
    T1.DEL_CREATEDTIME,
    T1.CREATEDBY,
    T1.RECVERSION,
    T1.RECID,
    T2.EXCEPTIONID,
    T2.PORTNAME,
    T2.MESSAGEID,
    T2.MESSAGESETID,
    T2.RECVERSION,
    T2.RECID,
    T3.PARTITIONKEY,
    T3.RECVERSION,
    T3.RECID,
    T1.DESCRIPTION,
    T1.ACTION
FROM
    SYSEXCEPTIONTABLE T1
    LEFT OUTER JOIN AIFEXCEPTIONMAP T2 ON
        (T1.RECID = T2.EXCEPTIONID)
    LEFT OUTER JOIN PARTITIONS T3 ON
        (T1.DATAPARTITION = T3.RECID)
WHERE
    T1.CREATEDBY = '4C4_WEBS'
	AND (T2.PORTNAME = 'uniPointSServices')
	AND  T1.CREATEDDATETIME >= '2019-10-01'
ORDER BY T1.CREATEDDATETIME
OPTION (FAST 20)
